/**
 * Pure Gen-7 PK7 (232-byte "stored"/box) decrypt, encrypt, and parse.
 *
 * No I/O, no Node APIs — `DataView`/`Uint8Array` only, safe for the
 * Cloudflare Workers runtime. This is the crypto core for USUM save
 * import (see the Phase 6 brief); there is no real .sav fixture, so
 * correctness for `decryptPk7`/`encryptPk7` is proven by a synthetic
 * encrypt -> decrypt round trip in tests/worker/pk7.test.ts.
 *
 * Algorithm (standard, documented Gen6/7 PKM format):
 * - Bytes 0x00..0x07 (Encryption Constant @0x00, checksum, sanity) are
 *   never encrypted or shuffled.
 * - Bytes 0x08..0xE7 (224 bytes = four 56-byte "blocks") are XOR'd, as
 *   u16 LE words, with a keystream generated by an LCG seeded with the
 *   Encryption Constant (EC): `seed = (seed * 0x41C64E6D + 0x6073) >>> 0`,
 *   XOR-ing each word with `seed >>> 16`. This is a symmetric stream
 *   cipher: applying it twice with the same EC returns the original data.
 * - The four blocks are additionally shuffled according to a 24-entry
 *   permutation table selected by `shuffleIndex = ((EC >> 13) & 31) % 24`.
 *   The permutation table below is the standard block-order table
 *   documented across Gen6/7 save tooling (e.g. PKHeX's PokeCrypto
 *   BlockPosition table).
 */

export type ParsedMon = {
  species: number;
  form: number;
  shiny: boolean;
  nickname: string | null;
  level: number | null;
  ivs: { hp: number; atk: number; def: number; spa: number; spd: number; spe: number } | null;
  evs: { hp: number; atk: number; def: number; spa: number; spd: number; spe: number } | null;
  moves: number[];
  otName: string | null;
  otId: string | null;
  heldItem: number | null;
  nature: number | null;
};

const PK7_SIZE = 232;
const HEADER_SIZE = 0x08;
const BLOCK_SIZE = 56;
const BLOCK_COUNT = 4;
const DATA_END = HEADER_SIZE + BLOCK_SIZE * BLOCK_COUNT; // 0xE8 === PK7_SIZE

/**
 * Standard 24-permutation block-order table for Gen6/7 PKM shuffling,
 * indexed by shuffleIndex (0..23). Row `i` lists, for each shuffled
 * block slot `b`, which canonical block index (0=A,1=B,2=C,3=D) occupies
 * that slot when EC yields shuffleIndex `i`.
 */
const BLOCK_POSITION: readonly (readonly number[])[] = [
  [0, 1, 2, 3],
  [0, 1, 3, 2],
  [0, 2, 1, 3],
  [0, 3, 1, 2],
  [0, 2, 3, 1],
  [0, 3, 2, 1],
  [1, 0, 2, 3],
  [1, 0, 3, 2],
  [2, 0, 1, 3],
  [3, 0, 1, 2],
  [2, 0, 3, 1],
  [3, 0, 2, 1],
  [1, 2, 0, 3],
  [1, 3, 0, 2],
  [2, 1, 0, 3],
  [3, 1, 0, 2],
  [2, 3, 0, 1],
  [3, 2, 0, 1],
  [1, 2, 3, 0],
  [1, 3, 2, 0],
  [2, 1, 3, 0],
  [3, 1, 2, 0],
  [2, 3, 1, 0],
  [3, 2, 1, 0],
];

const shuffleIndexFor = (ec: number): number => ((ec >>> 13) & 31) % 24;

/** XOR the 0x08..0xE7 region in place with the EC-seeded PRNG keystream. Self-inverse. */
const xorCryptInPlace = (buf: Uint8Array, ec: number): void => {
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  let seed = ec >>> 0;
  for (let offset = HEADER_SIZE; offset < DATA_END; offset += 2) {
    seed = (Math.imul(seed, 0x41c64e6d) + 0x6073) >>> 0;
    const value = view.getUint16(offset, true);
    view.setUint16(offset, (value ^ (seed >>> 16)) & 0xffff, true);
  }
};

/**
 * Unshuffle: for each shuffled block slot `b` in `src`, write it into
 * `dest` at the canonical block index `BLOCK_POSITION[shuffleIndex][b]`.
 */
const scatterBlocks = (src: Uint8Array, dest: Uint8Array, shuffleIndex: number): void => {
  const order = BLOCK_POSITION[shuffleIndex];
  for (let b = 0; b < BLOCK_COUNT; b++) {
    const destBlock = order[b];
    const srcOffset = HEADER_SIZE + b * BLOCK_SIZE;
    const destOffset = HEADER_SIZE + destBlock * BLOCK_SIZE;
    dest.set(src.subarray(srcOffset, srcOffset + BLOCK_SIZE), destOffset);
  }
};

/**
 * Shuffle (inverse of scatterBlocks): for each shuffled slot `b` in
 * `dest`, pull the canonical block `BLOCK_POSITION[shuffleIndex][b]`
 * from `src`.
 */
const gatherBlocks = (src: Uint8Array, dest: Uint8Array, shuffleIndex: number): void => {
  const order = BLOCK_POSITION[shuffleIndex];
  for (let b = 0; b < BLOCK_COUNT; b++) {
    const srcBlock = order[b];
    const srcOffset = HEADER_SIZE + srcBlock * BLOCK_SIZE;
    const destOffset = HEADER_SIZE + b * BLOCK_SIZE;
    dest.set(src.subarray(srcOffset, srcOffset + BLOCK_SIZE), destOffset);
  }
};

/**
 * Decrypt+unshuffle a 232-byte stored PK7 buffer into its canonical
 * (unshuffled, decrypted) 232-byte form. Pure; returns a new buffer.
 */
export function decryptPk7(stored: Uint8Array): Uint8Array {
  if (stored.length !== PK7_SIZE) {
    throw new Error(`decryptPk7: expected a ${PK7_SIZE}-byte buffer, got ${stored.length}`);
  }
  const ec = new DataView(stored.buffer, stored.byteOffset, stored.byteLength).getUint32(0, true);

  // XOR-decrypt on a private copy so the caller's buffer is never mutated.
  const decryptedShuffled = new Uint8Array(stored);
  xorCryptInPlace(decryptedShuffled, ec);

  const result = new Uint8Array(PK7_SIZE);
  result.set(decryptedShuffled.subarray(0, HEADER_SIZE), 0);
  scatterBlocks(decryptedShuffled, result, shuffleIndexFor(ec));
  return result;
}

/**
 * Encrypt+shuffle a canonical (unshuffled, decrypted) 232-byte PK7
 * buffer into its "stored" 232-byte form. Exact inverse of
 * `decryptPk7`: `decryptPk7(encryptPk7(d))` deep-equals `d`.
 */
export function encryptPk7(decrypted: Uint8Array): Uint8Array {
  if (decrypted.length !== PK7_SIZE) {
    throw new Error(`encryptPk7: expected a ${PK7_SIZE}-byte buffer, got ${decrypted.length}`);
  }
  const ec = new DataView(decrypted.buffer, decrypted.byteOffset, decrypted.byteLength).getUint32(0, true);

  const shuffled = new Uint8Array(PK7_SIZE);
  shuffled.set(decrypted.subarray(0, HEADER_SIZE), 0);
  gatherBlocks(decrypted, shuffled, shuffleIndexFor(ec));

  xorCryptInPlace(shuffled, ec);
  return shuffled;
}

/** Read up to `maxCodeUnits` UTF-16LE code units starting at `offset`, stopping at a 0x0000 terminator. */
const readUtf16String = (buf: Uint8Array, offset: number, maxCodeUnits: number): string | null => {
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  let out = "";
  for (let i = 0; i < maxCodeUnits; i++) {
    const codeUnit = view.getUint16(offset + i * 2, true);
    if (codeUnit === 0) break;
    out += String.fromCharCode(codeUnit);
  }
  return out.length > 0 ? out : null;
};

const NICKNAME_OFFSET = 0x40;
const NICKNAME_MAX_CODE_UNITS = 12;
const OT_NAME_OFFSET = 0xb0;
const OT_NAME_MAX_CODE_UNITS = 12;

/**
 * Parse a canonical (decrypted+unshuffled) 232-byte PK7 buffer into a
 * `ParsedMon`. Pure; `level` is always null (EXP -> level needs growth
 * rate tables, out of scope here). Species 0 is treated as an empty
 * box slot and returns a mostly-empty `ParsedMon` with `species: 0`.
 */
export function parsePk7(decrypted: Uint8Array): ParsedMon {
  if (decrypted.length !== PK7_SIZE) {
    throw new Error(`parsePk7: expected a ${PK7_SIZE}-byte buffer, got ${decrypted.length}`);
  }
  const view = new DataView(decrypted.buffer, decrypted.byteOffset, decrypted.byteLength);

  const species = view.getUint16(0x08, true);
  if (species === 0) {
    return {
      species: 0,
      form: 0,
      shiny: false,
      nickname: null,
      level: null,
      ivs: null,
      evs: null,
      moves: [],
      otName: null,
      otId: null,
      heldItem: null,
      nature: null,
    };
  }

  const heldItem = view.getUint16(0x0a, true);
  const tid = view.getUint16(0x0c, true);
  const sid = view.getUint16(0x0e, true);
  const pid = view.getUint32(0x18, true);
  const nature = decrypted[0x1c];
  // Form/gender byte: form is best-effort extracted from the upper bits
  // (gender + fateful-encounter occupy the low bits in the documented
  // Gen6/7 layout). Forms >31 spill into adjacent bits and are not
  // handled here.
  const form = decrypted[0x1d] >> 3;

  const evs = {
    hp: decrypted[0x1e],
    atk: decrypted[0x1f],
    def: decrypted[0x20],
    spa: decrypted[0x21],
    spd: decrypted[0x22],
    spe: decrypted[0x23],
  };

  const nickname = readUtf16String(decrypted, NICKNAME_OFFSET, NICKNAME_MAX_CODE_UNITS);

  const moves = [
    view.getUint16(0x5a, true),
    view.getUint16(0x5c, true),
    view.getUint16(0x5e, true),
    view.getUint16(0x60, true),
  ];

  const ivPacked = view.getUint32(0x74, true);
  const ivs = {
    hp: ivPacked & 0x1f,
    atk: (ivPacked >>> 5) & 0x1f,
    def: (ivPacked >>> 10) & 0x1f,
    spe: (ivPacked >>> 15) & 0x1f,
    spa: (ivPacked >>> 20) & 0x1f,
    spd: (ivPacked >>> 25) & 0x1f,
  };

  const otName = readUtf16String(decrypted, OT_NAME_OFFSET, OT_NAME_MAX_CODE_UNITS);

  const shiny = ((tid ^ sid ^ (pid >>> 16) ^ (pid & 0xffff)) >>> 0) < 16;

  return {
    species,
    form,
    shiny,
    nickname,
    level: null,
    ivs,
    evs,
    moves,
    otName,
    otId: String(tid),
    heldItem,
    nature,
  };
}
